### ISSUE TITLE
Error after upgrade from `0.6.1` to `0.8.5`

### ISSUE THREAD

**Issue by villander** [tildeio/ember-element-helper#116]
```json
"@ember/test-helpers": "3.2.0",
    "@embroider/addon-shim": "1.8.6",
    "@embroider/compat": "2.0.2",
    "@embroider/core": "2.0.2",
    "@embroider/macros": "1.13.2",
    "@embroider/router": "2.1.4",
    "@embroider/util": "1.12.0",
    "@embroider/webpack": "2.1.1",
    .....
    "ember-cli": "5.3.0",
    "ember-cli-app-version": "^6.0.1",
    "ember-cli-babel": "^7.26.11",
    ```
    
    
```
ERROR in ./node_modules/.pnpm/ember-animated@1.0.4_@ember+test-helpers@3.2.0_@glint+environment-ember-loose@1.2.1_@glint+te_cnni3bizkjkkf4pqlx3iihtj5m/node_modules/ember-animated/dist/components/animated-container.js
Module build failed (from ../../../../../../../../Users/villander/Projects/michael/mano-ui/node_modules/.pnpm/thread-loader@3.0.4_webpack@5.88.2/node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 2)
$TMPDIR/embroider/2012c7/node_modules/.pnpm/ember-animated@1.0.4_@ember+test-helpers@3.2.0_@glint+environment-ember-loose@1.2.1_@glint+te_cnni3bizkjkkf4pqlx3iihtj5m/node_modules/ember-animated/dist/components/animated-container.js: Missing helper: -element in node_modules/.pnpm/ember-animated@1.0.4_@ember+test-helpers@3.2.0_@glint+environment-ember-loose@1.2.1_@glint+te_cnni3bizkjkkf4pqlx3iihtj5m/node_modules/ember-animated/dist/components/animated-container.js

    at CompatResolver.reportError (/Users/villander/Projects/michael/app-ui/node_modules/.pnpm/@embroider+compat@2.0.2_patch_hash=xfwpwlobabhwhrnzagwhtrsove_@embroider+core@2.0.2/node_modules/@embroider/compat/src/resolver.js:219:21)
    at emit (/Users/villander/Projects/michael/app-ui/node_modules/.pnpm/@embroider+compat@2.0.2_patch_hash=xfwpwlobabhwhrnzagwhtrsove_@embroider+core@2.0.2/node_modules/@embroider/compat/src/resolver-transform.js:27:30)
    at SubExpression (/Users/villander/Projects/michael/app-ui/node_modules/.pnpm/@embroider+compat@2.0.2_patch_hash=xfwpwlobabhwhrnzagwhtrsove_@embroider+core@2.0.2/node_modules/@embroider/compat/src/resolver-transform.js:151:21)
    at visitNode ($TMPDIR/embroider/2012c7/node_modules/.pnpm/ember-source@5.3.0_@babel+core@7.23.2_@glimmer+component@1.1.2_@glint+template@1.2.1_rsvp@4.8.5_webpack@5.88.2/node_modules/ember-source/vendor/ember/ember-template-compiler.js:9201:16)
    at visitArray ($TMPDIR/embroider/2012c7/node_modules/.pnpm/ember-source@5.3.0_@babel+core@7.23.2_@glimmer+component@1.1.2_@glint+template@1.2.1_rsvp@4.8.5_webpack@5.88.2/node_modules/ember-source/vendor/ember/ember-template-compiler.js:9277:20)
    at visitKey ($TMPDIR/embroider/2012c7/node_modules/.pnpm/ember-source@5.3.0_@babel+core@7.23.2_@glimmer+component@1.1.2_@glint+template@1.2.1_rsvp@4.8.5_webpack@5.88.2/node_modules/ember-source/vendor/ember/ember-template-compiler.js:9256:7)
    at visitNode ($TMPDIR/embroider/2012c7/node_modules/.pnpm/ember-source@5.3.0_@babel+core@7.23.2_@glimmer+component@1.1.2_@glint+template@1.2.1_rsvp@4.8.5_webpack@5.88.2/node_modules/ember-source/vendor/ember/ember-template-compiler.js:9219:9)
    at visitArray ($TMPDIR/embroider/2012c7/node_modules/.pnpm/ember-source@5.3.0_@babel+core@7.23.2_@glimmer+component@1.1.2_@glint+template@1.2.1_rsvp@4.8.5_webpack@5.88.2/node_modules/ember-source/vendor/ember/ember-template-compiler.js:9277:20)
    at visitKey ($TMPDIR/embroider/2012c7/node_modules/.pnpm/ember-source@5.3.0_@babel+core@7.23.2_@glimmer+component@1.1.2_@glint+template@1.2.1_rsvp@4.8.5_webpack@5.88.2/node_modules/ember-source/vendor/ember/ember-template-compiler.js:9256:7)
    at visitNode ($TMPDIR/embroider/2012c7/node_modules/.pnpm/ember-source@5.3.0_@babel+core@7.23.2_@glimmer+component@1.1.2_@glint+template@1.2.1_rsvp@4.8.5_webpack@5.88.2/node_modules/ember-source/vendor/ember/ember-template-compiler.js:9219:9)
    at visitArray ($TMPDIR/embroider/2012c7/node_modules/.pnpm/ember-source@5.3.0_@babel+core@7.23.2_@glimmer+component@1.1.2_@glint+template@1.2.1_rsvp@4.8.5_webpack@5.88.2/node_modules/ember-source/vendor/ember/ember-template-compiler.js:9277:20)
    at visitKey ($TMPDIR/embroider/2012c7/node_modules/.pnpm/ember-source@5.3.0_@babel+core@7.23.2_@glimmer+component@1.1.2_@glint+template@1.2.1_rsvp@4.8.5_webpack@5.88.2/node_modules/ember-source/vendor/ember/ember-template-compiler.js:9256:7)
    at visitNode ($TMPDIR/embroider/2012c7/node_modules/.pnpm/ember-source@5.3.0_@babel+core@7.23.2_@glimmer+component@1.1.2_@glint+template@1.2.1_rsvp@4.8.5_webpack@5.88.2/node_modules/ember-source/vendor/ember/ember-template-compiler.js:9219:9)
    at visitArray ($TMPDIR/embroider/2012c7/node_modules/.pnpm/ember-source@5.3.0_@babel+core@7.23.2_@glimmer+component@1.1.2_@glint+template@1.2.1_rsvp@4.8.5_webpack@5.88.2/node_modules/ember-source/vendor/ember/ember-template-compiler.js:9277:20)
    at visitKey ($TMPDIR/embroider/2012c7/node_modules/.pnpm/ember-source@5.3.0_@babel+core@7.23.2_@glimmer+component@1.1.2_@glint+template@1.2.1_rsvp@4.8.5_webpack@5.88.2/node_modules/ember-source/vendor/ember/ember-template-compiler.js:9256:7)
    at visitNode ($TMPDIR/embroider/2012c7/node_modules/.pnpm/ember-source@5.3.0_@babel+core@7.23.2_@glimmer+component@1.1.2_@glint+template@1.2.1_rsvp@4.8.5_webpack@5.88.2/node_modules/ember-source/vendor/ember/ember-template-compiler.js:9219:9)
    at visitKey ($TMPDIR/embroider/2012c7/node_modules/.pnpm/ember-source@5.3.0_@babel+core@7.23.2_@glimmer+component@1.1.2_@glint+template@1.2.1_rsvp@4.8.5_webpack@5.88.2/node_modules/ember-source/vendor/ember/ember-template-compiler.js:9259:20)
    at visitNode ($TMPDIR/embroider/2012c7/node_modules/.pnpm/ember-source@5.3.0_@babel+core@7.23.2_@glimmer+component@1.1.2_@glint+template@1.2.1_rsvp@4.8.5_webpack@5.88.2/node_modules/ember-source/vendor/ember/ember-template-compiler.js:9219:9)
    at visitArray ($TMPDIR/embroider/2012c7/node_modules/.pnpm/ember-source@5.3.0_@babel+core@7.23.2_@glimmer+component@1.1.2_@glint+template@1.2.1_rsvp@4.8.5_webpack@5.88.2/node_modules/ember-source/vendor/ember/ember-template-compiler.js:9277:20)
    at visitKey ($TMPDIR/embroider/2012c7/node_modules/.pnpm/ember-source@5.3.0_@babel+core@7.23.2_@glimmer+component@1.1.2_@glint+template@1.2.1_rsvp@4.8.5_webpack@5.88.2/node_modules/ember-source/vendor/ember/ember-template-compiler.js:9256:7)
    at visitNode ($TMPDIR/embroider/2012c7/node_modules/.pnpm/ember-source@5.3.0_@babel+core@7.23.2_@glimmer+component@1.1.2_@glint+template@1.2.1_rsvp@4.8.5_webpack@5.88.2/node_modules/ember-source/vendor/ember/ember-template-compiler.js:9219:9)
    at traverse ($TMPDIR/embroider/2012c7/node_modules/.pnpm/ember-source@5.3.0_@babel+core@7.23.2_@glimmer+component@1.1.2_@glint+template@1.2.1_rsvp@4.8.5_webpack@5.88.2/node_modules/ember-source/vendor/ember/ember-template-compiler.js:9314:5)
    at preprocess ($TMPDIR/embroider/2012c7/node_modules/.pnpm/ember-source@5.3.0_@babel+core@7.23.2_@glimmer+component@1.1.2_@glint+template@1.2.1_rsvp@4.8.5_webpack@5.88.2/node_modules/ember-source/vendor/ember/ember-template-compiler.js:10640:9)
    at normalize ($TMPDIR/embroider/2012c7/node_modules/.pnpm/ember-source@5.3.0_@babel+core@7.23.2_@glimmer+component@1.1.2_@glint+template@1.2.1_rsvp@4.8.5_webpack@5.88.2/node_modules/ember-source/vendor/ember/ember-template-compiler.js:11180:15)
    at precompileJSON ($TMPDIR/embroider/2012c7/node_modules/.pnpm/ember-source@5.3.0_@babel+core@7.23.2_@glimmer+component@1.1.2_@glint+template@1.2.1_rsvp@4.8.5_webpack@5.88.2/node_modules/ember-source/vendor/ember/ember-template-compiler.js:4981:47)
    at precompile ($TMPDIR/embroider/2012c7/node_modules/.pnpm/ember-source@5.3.0_@babel+core@7.23.2_@glimmer+component@1.1.2_@glint+template@1.2.1_rsvp@4.8.5_webpack@5.88.2/node_modules/ember-source/vendor/ember/ember-template-compiler.js:5014:31)
    at Object.precompile ($TMPDIR/embroider/2012c7/node_modules/.pnpm/ember-source@5.3.0_@babel+core@7.23.2_@glimmer+component@1.1.2_@glint+template@1.2.1_rsvp@4.8.5_webpack@5.88.2/node_modules/ember-source/vendor/ember/ember-template-compiler.js:16274:37)
    at insertCompiledTemplate (/Users/villander/Projects/michael/app-ui/node_modules/.pnpm/babel-plugin-ember-template-compilation@2.0.0/node_modules/babel-plugin-ember-template-compilation/src/plugin.js:197:64)
    at PluginPass.CallExpression (/Users/villander/Projects/michael/app-ui/node_modules/.pnpm/babel-plugin-ember-template-compilation@2.0.0/node_modules/babel-plugin-ember-template-compilation/src/plugin.js:129:25)
    at PluginPass.<anonymous> (/Users/villander/Projects/michael/app-ui/node_modules/.pnpm/@embroider+core@2.0.2/node_modules/@embroider/core/src/portable-babel-launcher.js:37:29)
    at newFn (/Users/villander/Projects/michael/app-ui/node_modules/.pnpm/@babel+traverse@7.23.2_supports-color@8.1.1/node_modules/@babel/traverse/lib/visitors.js:159:14)
    at NodePath._call (/Users/villander/Projects/michael/app-ui/node_modules/.pnpm/@babel+traverse@7.23.2_supports-color@8.1.1/node_modules/@babel/traverse/lib/path/context.js:46:20)
    at NodePath.call (/Users/villander/Projects/michael/app-ui/node_modules/.pnpm/@babel+traverse@7.23.2_supports-color@8.1.1/node_modules/@babel/traverse/lib/path/context.js:36:17)
    at NodePath.visit (/Users/villander/Projects/michael/app-ui/node_modules/.pnpm/@babel+traverse@7.23.2_supports-color@8.1.1/node_modules/@babel/traverse/lib/path/context.js:82:31)
    at TraversalContext.visitQueue (/Users/villander/Projects/michael/app-ui/node_modules/.pnpm/@babel+traverse@7.23.2_supports-color@8.1.1/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitSingle (/Users/villander/Projects/michael/app-ui/node_modules/.pnpm/@babel+traverse@7.23.2_supports-color@8.1.1/node_modules/@babel/traverse/lib/context.js:65:19)
    at TraversalContext.visit (/Users/villander/Projects/michael/app-ui/node_modules/.pnpm/@babel+traverse@7.23.2_supports-color@8.1.1/node_modules/@babel/traverse/lib/context.js:109:19)
    at traverseNode (/Users/villander/Projects/michael/app-ui/node_modules/.pnpm/@babel+traverse@7.23.2_supports-color@8.1.1/node_modules/@babel/traverse/lib/traverse-node.js:22:17)
    at NodePath.visit (/Users/villander/Projects/michael/app-ui/node_modules/.pnpm/@babel+traverse@7.23.2_supports-color@8.1.1/node_modules/@babel/traverse/lib/path/context.js:88:52)
    at TraversalContext.visitQueue (/Users/villander/Projects/michael/app-ui/node_modules/.pnpm/@babel+traverse@7.23.2_supports-color@8.1.1/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitMultiple (/Users/villander/Projects/michael/app-ui/node_modules/.pnpm/@babel+traverse@7.23.2_supports-color@8.1.1/node_modules/@babel/traverse/lib/context.js:61:17)
    at TraversalContext.visit (/Users/villander/Projects/michael/app-ui/node_modules/.pnpm/@babel+traverse@7.23.2_supports-color@8.1.1/node_modules/@babel/traverse/lib/context.js:107:19)
    at traverseNode (/Users/villander/Projects/michael/app-ui/node_modules/.pnpm/@babel+traverse@7.23.2_supports-color@8.1.1/node_modules/@babel/traverse/lib/traverse-node.js:22:17)
    at NodePath.visit (/Users/villander/Projects/michael/app-ui/node_modules/.pnpm/@babel+traverse@7.23.2_supports-color@8.1.1/node_modules/@babel/traverse/lib/path/context.js:88:52)
    at TraversalContext.visitQueue (/Users/villander/Projects/michael/app-ui/node_modules/.pnpm/@babel+traverse@7.23.2_supports-color@8.1.1/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitMultiple (/Users/villander/Projects/michael/app-ui/node_modules/.pnpm/@babel+traverse@7.23.2_supports-color@8.1.1/node_modules/@babel/traverse/lib/context.js:61:17)
    at TraversalContext.visit (/Users/villander/Projects/michael/app-ui/node_modules/.pnpm/@babel+traverse@7.23.2_supports-color@8.1.1/node_modules/@babel/traverse/lib/context.js:107:19)
    at traverseNode (/Users/villander/Projects/michael/app-ui/node_modules/.pnpm/@babel+traverse@7.23.2_supports-color@8.1.1/node_modules/@babel/traverse/lib/traverse-node.js:22:17)
    at NodePath.visit (/Users/villander/Projects/michael/app-ui/node_modules/.pnpm/@babel+traverse@7.23.2_supports-color@8.1.1/node_modules/@babel/traverse/lib/path/context.js:88:52)
    at TraversalContext.visitQueue (/Users/villander/Projects/michael/app-ui/node_modules/.pnpm/@babel+traverse@7.23.2_supports-color@8.1.1/node_modules/@babel/traverse/lib/context.js:86:16)
 @ ./components/animated-container.js 1:0-74 1:0-74
 @ ./components/notes/note-board/index.hbs 5:0-60 120:64-81
 @ ./components/notes/note-board/index.ts 7:0-35 39:21-29
 @ ./tests/integration/components/notes/note-board/component-test.ts 2:0-81 35:22-36 58:22-36 91:22-36 119:22-36 159:22-36 191:24-38 215:24-38 240:24-38
 @ ./assets/test.js 191:13-90

webpack 5.88.2 compiled with 1 error in 18522 ms
Build Error (PackagerRunner) in node_modules/.pnpm/ember-animated@1.0.4_@ember+test-helpers@3.2.0_@glint+environment-ember-loose@1.2.1_@glint+te_cnni3bizkjkkf4pqlx3iihtj5m/node_modules/ember-animated/dist/components/animated-container.js

Module build failed (from ../../../../../../../../Users/villander/Projects/michael/app-ui/node_modules/.pnpm/thread-loader@3.0.4_webpack@5.88.2/node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 2)
$TMPDIR/embroider/2012c7/node_modules/.pnpm/ember-animated@1.0.4_@ember+test-helpers@3.2.0_@glint+environment-ember-loose@1.2.1_@glint+te_cnni3bizkjkkf4pqlx3iihtj5m/node_modules/ember-animated/dist/components/animated-container.js/animated-container.js: Missing helper: -element in node_modules/.pnpm/ember-animated@1.0.4_@ember+test-helpers@3.2.0_@glint+environment-ember-loose@1.2.1_@glint+te_cnni3bizkjkkf4pqlx3iihtj5m/node_modules/ember-animated/dist/components/animated-container.js

    at CompatResolver.reportError (/Users/villander/Projects/michael/app-ui/node_modules/.pnpm/@embroider+compat@2.0.2_patch_hash=xfwpwlobabhwhrnzagwhtrsove_@embroider+core@2.0.2/node_modules/@embroider/compat/src/resolver.js:219:21)
    at emit (/Users/villander/Projects/michael/app-ui/node_modules/.pnpm/@embroider+compat@2.0.2_patch_hash=xfwpwlobabhwhrnzagwhtrsove_@embroider+core@2.0.2/node_modules/@embroider/compat/src/resolver-transform.js:27:30)
    at SubExpression (/Users/villander/Projects/michael/app-ui/node_modules/.pnpm/@embroider+compat@2.0.2_patch_hash=xfwpwlobabhwhrnzagwhtrsove_@embroider+core@2.0.2/node_modules/@embroider/compat/src/resolver-transform.js:151:21)
    at visitNode ($TMPDIR/embroider/2012c7/node_modules/.pnpm/ember-source@5.3.0_@babel+core@7.23.2_@glimmer+component@1.1.2_@glint+template@1.2.1_rsvp@4.8.5_webpack@5.88.2/node_modules/ember-source/vendor/ember/ember-template-compiler.js:9201:16)
    at visitArray ($TMPDIR/embroider/2012c7/node_modules/.pnpm/ember-source@5.3.0_@babel+core@7.23.2_@glimmer+component@1.1.2_@glint+template@1.2.1_rsvp@4.8.5_webpack@5.88.2/node_modules/ember-source/vendor/ember/ember-template-compiler.js:9277:20)
    at visitKey ($TMPDIR/embroider/2012c7/node_modules/.pnpm/ember-source@5.3.0_@babel+core@7.23.2_@glimmer+component@1.1.2_@glint+template@1.2.1_rsvp@4.8.5_webpack@5.88.2/node_modules/ember-source/vendor/ember/ember-template-compiler.js:9256:7)
    at visitNode ($TMPDIR/embroider/2012c7/node_modules/.pnpm/ember-source@5.3.0_@babel+core@7.23.2_@glimmer+component@1.1.2_@glint+template@1.2.1_rsvp@4.8.5_webpack@5.88.2/node_modules/ember-source/vendor/ember/ember-template-compiler.js:9219:9)
    at visitArray ($TMPDIR/embroider/2012c7/node_modules/.pnpm/ember-source@5.3.0_@babel+core@7.23.2_@glimmer+component@1.1.2_@glint+template@1.2.1_rsvp@4.8.5_webpack@5.88.2/node_modules/ember-source/vendor/ember/ember-template-compiler.js:9277:20)
    at visitKey ($TMPDIR/embroider/2012c7/node_modules/.pnpm/ember-source@5.3.0_@babel+core@7.23.2_@glimmer+component@1.1.2_@glint+template@1.2.1_rsvp@4.8.5_webpack@5.88.2/node_modules/ember-source/vendor/ember/ember-template-compiler.js:9256:7)
    at visitNode ($TMPDIR/embroider/2012c7/node_modules/.pnpm/ember-source@5.3.0_@babel+core@7.23.2_@glimmer+component@1.1.2_@glint+template@1.2.1_rsvp@4.8.5_webpack@5.88.2/node_modules/ember-source/vendor/ember/ember-template-compiler.js:9219:9)
    at visitArray ($TMPDIR/embroider/2012c7/node_modules/.pnpm/ember-source@5.3.0_@babel+core@7.23.2_@glimmer+component@1.1.2_@glint+template@1.2.1_rsvp@4.8.5_webpack@5.88.2/node_modules/ember-source/vendor/ember/ember-template-compiler.js:9277:20)
    at visitKey ($TMPDIR/embroider/2012c7/node_modules/.pnpm/ember-source@5.3.0_@babel+core@7.23.2_@glimmer+component@1.1.2_@glint+template@1.2.1_rsvp@4.8.5_webpack@5.88.2/node_modules/ember-source/vendor/ember/ember-template-compiler.js:9256:7)
    at visitNode ($TMPDIR/embroider/2012c7/node_modules/.pnpm/ember-source@5.3.0_@babel+core@7.23.2_@glimmer+component@1.1.2_@glint+template@1.2.1_rsvp@4.8.5_webpack@5.88.2/node_modules/ember-source/vendor/ember/ember-template-compiler.js:9219:9)
    at visitArray ($TMPDIR/embroider/2012c7/node_modules/.pnpm/ember-source@5.3.0_@babel+core@7.23.2_@glimmer+component@1.1.2_@glint+template@1.2.1_rsvp@4.8.5_webpack@5.88.2/node_modules/ember-source/vendor/ember/ember-template-compiler.js:9277:20)
    at visitKey ($TMPDIR/embroider/2012c7/node_modules/.pnpm/ember-source@5.3.0_@babel+core@7.23.2_@glimmer+component@1.1.2_@glint+template@1.2.1_rsvp@4.8.5_webpack@5.88.2/node_modules/ember-source/vendor/ember/ember-template-compiler.js:9256:7)
    at visitNode ($TMPDIR/embroider/2012c7/node_modules/.pnpm/ember-source@5.3.0_@babel+core@7.23.2_@glimmer+component@1.1.2_@glint+template@1.2.1_rsvp@4.8.5_webpack@5.88.2/node_modules/ember-source/vendor/ember/ember-template-compiler.js:9219:9)
    at visitKey ($TMPDIR/embroider/2012c7/node_modules/.pnpm/ember-source@5.3.0_@babel+core@7.23.2_@glimmer+component@1.1.2_@glint+template@1.2.1_rsvp@4.8.5_webpack@5.88.2/node_modules/ember-source/vendor/ember/ember-template-compiler.js:9259:20)
    at visitNode ($TMPDIR/embroider/2012c7/node_modules/.pnpm/ember-source@5.3.0_@babel+core@7.23.2_@glimmer+component@1.1.2_@glint+template@1.2.1_rsvp@4.8.5_webpack@5.88.2/node_modules/ember-source/vendor/ember/ember-template-compiler.js:9219:9)
    at visitArray ($TMPDIR/embroider/2012c7/node_modules/.pnpm/ember-source@5.3.0_@babel+core@7.23.2_@glimmer+component@1.1.2_@glint+template@1.2.1_rsvp@4.8.5_webpack@5.88.2/node_modules/ember-source/vendor/ember/ember-template-compiler.js:9277:20)
    at visitKey ($TMPDIR/embroider/2012c7/node_modules/.pnpm/ember-source@5.3.0_@babel+core@7.23.2_@glimmer+component@1.1.2_@glint+template@1.2.1_rsvp@4.8.5_webpack@5.88.2/node_modules/ember-source/vendor/ember/ember-template-compiler.js:9256:7)
    at visitNode ($TMPDIR/embroider/2012c7/node_modules/.pnpm/ember-source@5.3.0_@babel+core@7.23.2_@glimmer+component@1.1.2_@glint+template@1.2.1_rsvp@4.8.5_webpack@5.88.2/node_modules/ember-source/vendor/ember/ember-template-compiler.js:9219:9)
    at traverse ($TMPDIR/embroider/2012c7/node_modules/.pnpm/ember-source@5.3.0_@babel+core@7.23.2_@glimmer+component@1.1.2_@glint+template@1.2.1_rsvp@4.8.5_webpack@5.88.2/node_modules/ember-source/vendor/ember/ember-template-compiler.js:9314:5)
    at preprocess ($TMPDIR/embroider/2012c7/node_modules/.pnpm/ember-source@5.3.0_@babel+core@7.23.2_@glimmer+component@1.1.2_@glint+template@1.2.1_rsvp@4.8.5_webpack@5.88.2/node_modules/ember-source/vendor/ember/ember-template-compiler.js:10640:9)
    at normalize ($TMPDIR/embroider/2012c7/node_modules/.pnpm/ember-source@5.3.0_@babel+core@7.23.2_@glimmer+component@1.1.2_@glint+template@1.2.1_rsvp@4.8.5_webpack@5.88.2/node_modules/ember-source/vendor/ember/ember-template-compiler.js:11180:15)
    at precompileJSON ($TMPDIR/embroider/2012c7/node_modules/.pnpm/ember-source@5.3.0_@babel+core@7.23.2_@glimmer+component@1.1.2_@glint+template@1.2.1_rsvp@4.8.5_webpack@5.88.2/node_modules/ember-source/vendor/ember/ember-template-compiler.js:4981:47)
    at precompile ($TMPDIR/embroider/2012c7/node_modules/.pnpm/ember-source@5.3.0_@babel+core@7.23.2_@glimmer+component@1.1.2_@glint+template@1.2.1_rsvp@4.8.5_webpack@5.88.2/node_modules/ember-source/vendor/ember/ember-template-compiler.js:5014:31)
    at Object.precompile ($TMPDIR/embroider/2012c7/node_modules/.pnpm/ember-source@5.3.0_@babel+core@7.23.2_@glimmer+component@1.1.2_@glint+template@1.2.1_rsvp@4.8.5_webpack@5.88.2/node_modules/ember-source/vendor/ember/ember-template-compiler.js:16274:37)
    at insertCompiledTemplate (/Users/villander/Projects/michael/app-ui/node_modules/.pnpm/babel-plugin-ember-template-compilation@2.0.0/node_modules/babel-plugin-ember-template-compilation/src/plugin.js:197:64)
    at PluginPass.CallExpression (/Users/villander/Projects/michael/app-ui/node_modules/.pnpm/babel-plugin-ember-template-compilation@2.0.0/node_modules/babel-plugin-ember-template-compilation/src/plugin.js:129:25)
    at PluginPass.<anonymous> (/Users/villander/Projects/michael/app-ui/node_modules/.pnpm/@embroider+core@2.0.2/node_modules/@embroider/core/src/portable-babel-launcher.js:37:29)
    at newFn (/Users/villander/Projects/michael/app-ui/node_modules/.pnpm/@babel+traverse@7.23.2_supports-color@8.1.1/node_modules/@babel/traverse/lib/visitors.js:159:14)
    at NodePath._call (/Users/villander/Projects/michael/app-ui/node_modules/.pnpm/@babel+traverse@7.23.2_supports-color@8.1.1/node_modules/@babel/traverse/lib/path/context.js:46:20)
    at NodePath.call (/Users/villander/Projects/michael/app-ui/node_modules/.pnpm/@babel+traverse@7.23.2_supports-color@8.1.1/node_modules/@babel/traverse/lib/path/context.js:36:17)
    at NodePath.visit (/Users/villander/Projects/michael/app-ui/node_modules/.pnpm/@babel+traverse@7.23.2_supports-color@8.1.1/node_modules/@babel/traverse/lib/path/context.js:82:31)
    at TraversalContext.visitQueue (/Users/villander/Projects/michael/app-ui/node_modules/.pnpm/@babel+traverse@7.23.2_supports-color@8.1.1/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitSingle (/Users/villander/Projects/michael/app-ui/node_modules/.pnpm/@babel+traverse@7.23.2_supports-color@8.1.1/node_modules/@babel/traverse/lib/context.js:65:19)
    at TraversalContext.visit (/Users/villander/Projects/michael/app-ui/node_modules/.pnpm/@babel+traverse@7.23.2_supports-color@8.1.1/node_modules/@babel/traverse/lib/context.js:109:19)
    at traverseNode (/Users/villander/Projects/michael/app-ui/node_modules/.pnpm/@babel+traverse@7.23.2_supports-color@8.1.1/node_modules/@babel/traverse/lib/traverse-node.js:22:17)
    at NodePath.visit (/Users/villander/Projects/michael/app-ui/node_modules/.pnpm/@babel+traverse@7.23.2_supports-color@8.1.1/node_modules/@babel/traverse/lib/path/context.js:88:52)
    at TraversalContext.visitQueue (/Users/villander/Projects/michael/app-ui/node_modules/.pnpm/@babel+traverse@7.23.2_supports-color@8.1.1/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitMultiple (/Users/villander/Projects/michael/app-ui/node_modules/.pnpm/@babel+traverse@7.23.2_supports-color@8.1.1/node_modules/@babel/traverse/lib/context.js:61:17)
    at TraversalContext.visit (/Users/villander/Projects/michael/app-ui/node_modules/.pnpm/@babel+traverse@7.23.2_supports-color@8.1.1/node_modules/@babel/traverse/lib/context.js:107:19)
    at traverseNode (/Users/villander/Projects/michael/app-ui/node_modules/.pnpm/@babel+traverse@7.23.2_supports-color@8.1.1/node_modules/@babel/traverse/lib/traverse-node.js:22:17)
    at NodePath.visit (/Users/villander/Projects/michael/app-ui/node_modules/.pnpm/@babel+traverse@7.23.2_supports-color@8.1.1/node_modules/@babel/traverse/lib/path/context.js:88:52)
    at TraversalContext.visitQueue (/Users/villander/Projects/michael/app-ui/node_modules/.pnpm/@babel+traverse@7.23.2_supports-color@8.1.1/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitMultiple (/Users/villander/Projects/michael/app-ui/node_modules/.pnpm/@babel+traverse@7.23.2_supports-color@8.1.1/node_modules/@babel/traverse/lib/context.js:61:17)
    at TraversalContext.visit (/Users/villander/Projects/michael/app-ui/node_modules/.pnpm/@babel+traverse@7.23.2_supports-color@8.1.1/node_modules/@babel/traverse/lib/context.js:107:19)
    at traverseNode (/Users/villander/Projects/michael/app-ui/node_modules/.pnpm/@babel+traverse@7.23.2_supports-color@8.1.1/node_modules/@babel/traverse/lib/traverse-node.js:22:17)
    at NodePath.visit (/Users/villander/Projects/michael/app-ui/node_modules/.pnpm/@babel+traverse@7.23.2_supports-color@8.1.1/node_modules/@babel/traverse/lib/path/context.js:88:52)
    at TraversalContext.visitQueue (/Users/villander/Projects/michael/app-ui/node_modules/.pnpm/@babel+traverse@7.23.2_supports-color@8.1.1/node_modules/@babel/traverse/lib/context.js:86:16)


Stack Trace and Error Report: /var/folders/0v/jpdg1flj3qscvbvt728pgt8c0000gn/T/error.dump.1f9810e88f55a4e3fa5a36a5dce6bd1c.log
```

**Comment by villander** [comment]
@NullVoxPopuli any idea what's going on here?

**Comment by NullVoxPopuli** [comment]
Not sure, can you first try getting to v3.x of embroider?
