### ISSUE TITLE
Uncaught Error: Assertion Failed: The `element` helper polyfill encountered an unexpected error

### ISSUE THREAD

**Issue by glbatistabh** [tildeio/ember-element-helper#92]
Hi! Please can someone help me with this error?
I can't solve it and I'm thinking it's a bug.

**Error:**
```
Uncaught Error: Assertion Failed: The `element` helper polyfill encountered an unexpected error. Please report the issue at http://github.com/tildeio/ember-element-helper with the usage and conditions that caused this error.
    at assert (index.js:181:1)
    at element.js:14:1
    at index.js:5258:1
    at deprecateMutationsInTrackingTransaction (validator.js:191:1)
    at index.js:5257:1
    at SimpleClassicHelperManager.getValue (index.js:5268:1)
    at manager.js:971:1
    at reference.js:170:1
    at track (validator.js:835:1)
    at valueForRef (reference.js:169:1)
```

**package.json**
```
shell>cat package.json | grep leaflet
    "ember-leaflet": "^5.0.1",
    "leaflet": "^1.8.0",
```

**Environment:**
```
shell>ember -v
ember-cli: 3.28.5
node: 14.15.5
os: linux x64
```

**Printscreen:**
![image](https://user-images.githubusercontent.com/8257020/190023885-67e52ed1-59cb-411b-9251-645d49a9dcee.png)

**Comment by brianjgeiger** [comment]
Upgrading ember-element-helper to 0.6.1 fixed the problem with ember-cli-meta-tags, but I'm getting the same problem with one of our internal uses of the element helper now, so I'll investigate that further.

**Comment by brianjgeiger** [comment]
I followed the suggestions on this thread - https://github.com/tildeio/ember-element-helper/issues/84 - and pinned the resolution of the version of ember-element-helper to 0.6.1 in the package.json. That fixed my problems; apparently different addons were using different versions, which caused the problems above.

**Comment by glbatistabh** [comment]
I also tried to pinned the version of ember-element-helper (`ember install ember-element-helper@^0.6.1`) in my package.json, but it didn't work for me... :-(

**Comment by glbatistabh** [comment]
> I followed the suggestions on this thread - #84 - and pinned the resolution of the version of ember-element-helper to 0.6.1 in the package.json. That fixed my problems; apparently different addons were using different versions, which caused the problems above.

@brianjgeiger can you share your `package.json` file with me?

**Comment by brianjgeiger** [comment]
Sure, you can find the diff with my changes at https://github.com/CenterForOpenScience/ember-osf-web/pull/1660/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519
